### ISSUE TITLE
Chrome extension went MIA 

### ISSUE THREAD

**Issue by complexlummox** [joelpt/sidewise#45]
Hai & thank youse for this genius tool. 
The other day, SideWise disappeared from my browser:
Instead of the light-bulb, it showed the blank extension icon and going to the extension's page in the Chrome Store brought back a 404 Error. 
I rediscovered it today via search box. Understandably, all my previous data is gone (not a big deal) But do you know what happened?

**Comment by joelpt** [comment]
I don't know what happened and have never seen this kind of problem before.

I am going to close this issue now since it was reported in 2013 - if you believe this is still an issue please feel free to reopen it.
