### ISSUE TITLE
Sometimes don't save new tabs, and always restart at same pages in memory. Database is 10,5 mb, there any limitation of size?

### ISSUE THREAD

**Issue by renanoliveira0** [joelpt/sidewise#59]

**Comment by joelpt** [comment]
The data corruption issues surrounding having several thousand tabs should now be fixed. Sidewise should now be able to store an essentially unlimited number of tabs. It is now using chrome.storage.local for storing the tree data, which has no maximum storage limit.

Please let me know if you see any further issues of this type.

**Comment by renanoliveira0** [comment]
OK! Thanks very much!!!
